name: Nightly Cucumber Regression

on:
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch:
    # Allows manual trigger from the GitHub Actions tab

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Run Maven Tests (Headless)
        run: mvn clean install -Dcucumber.filter.tags="@regression" -Dheadless=true

      - name: Upload Test Report Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nightly-cucumber-report
          path: target/surefire-reports/
          retention-days: 7