name: Nightly Cucumber Regression

on:
  schedule:
    - cron: '0 17 * * *'  # Runs every night at 10:30 PM IST
  workflow_dispatch:       # Manual trigger option

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Maven Tests (Headless)
        working-directory: ./TestCopilot
        run: mvn clean install -Dcucumber.filter.tags="@regression" -Dheadless=true
